# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzZmZWYyNTBiOTUxOTczNzZhZjBlY2YxNzA5YjIxNjgzMGJjNmRiZmNkYmIzNTc4YTVkYmI1ZWE3ODBkNmUwNTZlODllYzU2ZGU0NjA1Yzk2ZGNlNjQwMWMxM2FmNzZmZDcyMzJmMzcyNTMzYjI0ZTg1MDQwMTFiYWVlZGQ0ZWQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
